/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#391713',
        secondary: '#E95322',
        'light-red': '#FF642F',
        yellow: '#F5CB58',
        cream: '#F3E9B5',
        peach: '#FFDECF',
        dark: '#252525',
        'gray-icon': '#676767',
        'gray-light': '#F5F5F5',
        'gray-bg': '#F8F8F8',
        'gray-input': '#E8E8E8',
        'gray-muted': '#8E8E8E',
        'peach-light': '#F0E0D8',
      },
      fontFamily: {
        primary: ['LeagueSpartan-Regular'],
        'primary-light': ['LeagueSpartan-Light'],
        'primary-medium': ['LeagueSpartan-Medium'],
        'primary-semibold': ['LeagueSpartan-SemiBold'],
        'primary-bold': ['LeagueSpartan-Bold'],
        'primary-extrabold': ['LeagueSpartan-ExtraBold'],
        secondary: ['Poppins-Regular'],
        'secondary-light': ['Poppins-Light'],
        'secondary-medium': ['Poppins-Medium'],
        'secondary-semibold': ['Poppins-SemiBold'],
        'secondary-bold': ['Poppins-Bold'],
        'secondary-extrabold': ['Poppins-ExtraBold'],
        'tertiary-black': ['Inter-Black'],
      },
      fontSize: {
        xs: 12,
        sm: 14,
        base: 16,
        lg: 18,
        xl: 20,
        '2xl': 24,
        '3xl': 30,
        '4xl': 36,
        '5xl': 48,
        '6xl': 60,
        '7xl': 72,
        '8xl': 96,
        '9xl': 128,

        13: '13px',
        15: '15px',
        17: '17px',
        24: '24px',
        28: '28px',
        32: '32px',
        33: '33px',
        35: '34.85px',
        50: '50px',
      },
      borderRadius: {
        20: '20px',
        30: '30px',
        36: '36px',
        50: '50px',
        75: '75px',
        100: '100px',
        200: '200px',
      },
      borderWidth: {
        3: '3px',
        5: '5px',
        10: '10px',
      },
      lineHeight: {
        4.5: '18px',
        6.5: '26px',
      },
      spacing: {
        7.5: '30px',
        49: '49px',
        62: '62px',
        71: '71px',
        80: '80px',
        100: '100px',
        108: '108px',
        120: '120px',
        130: '130px',
        140: '140px',
        170: '170px',
        180: '180px',
        200: '200px',
      },
      fontWeight: {},
    },
  },
  plugins: [],
};
